server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/keep_account?useSSL=false&serverTimezone=UTC
    username: root
    password: 2917548a
